apiVersion: v1
kind: Service
metadata:
  name: treetracker-web-map-client-svc-main
  labels:
    app: treetracker-web-map-client-main
    name: treetracker-web-map-client-svc-main
  namespace: webmap
spec:
  selector:
    app: treetracker-web-map-client-main
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 3030
