apiVersion: apps/v1
kind: Deployment
metadata:
  name: treetracker-web-map-client
  namespace: webmap
  labels:
    app: treetracker-web-map-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: treetracker-web-map-client
  template:
    metadata:
      labels:
        app: treetracker-web-map-client
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: doks.digitalocean.com/node-pool
                    operator: In
                    values:
                      - microservices-node-pool
      containers:
        - name: treetracker-web-map-client
          image: greenstand/treetracker-web-map-client:TAG
          env:
            - name: NEXT_PUBLIC_API
              value: https://prod-k8s.treetracker.org/query
            - name: NEXT_PUBLIC_TILE_SERVER_URL
              value: https://{s}.treetracker.org/tiles/
            - name: NEXT_PUBLIC_TILE_SERVER_SUBDOMAINS
              value: prod-k8s
