apiVersion: apps/v1
kind: Deployment
metadata:
  name: treetracker-web-map-client-beta
  namespace: webmap
  labels:
    app: treetracker-web-map-client-beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: treetracker-web-map-client-beta
  template:
    metadata:
      labels:
        app: treetracker-web-map-client-beta
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: doks.digitalocean.com/node-pool
                    operator: In
                    values:
                      - microservices-node-pool
      containers:
        - name: treetracker-web-map-client
          image: greenstand/treetracker-web-map-client:TAG
          env:
            - name: NEXT_PUBLIC_API
              value: https://dev-k8s.treetracker.org/query
            - name: NEXT_PUBLIC_TILE_SERVER_URL
              value: https://{s}.treetracker.org/tiles/
            - name: NEXT_PUBLIC_TILE_SERVER_SUBDOMAINS
              value: dev-k8s
            - name: NEXT_PUBLIC_TILE_SERVER_WEBMAP_API
              value: https://dev-k8s.treetracker.org/webmap/
            - name: NEXT_PUBLIC_COUNTRY_LEADER_BOARD_DISABLED
              value: true
