apiVersion: v1
kind: Service
metadata:
  name: treetracker-web-map-client-beta-ambassador-svc
  labels:
    app: treetracker-web-map-client-beta
    name: treetracker-web-map-client-bate-ambassador-svc
  namespace: webmap
spec:
  selector:
    app: treetracker-web-map-client-beta
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
